"""add user_id to runs for per-user history

Revision ID: 99b4c08fd112
Revises: ffc188ece671
Create Date: 2026-09-14 08:16:11.115362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b4c08fd112'
down_revision: Union[str, Sequence[str], None] = 'ffc188ece671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index('ix_runs_user_id', 'runs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runs_user_id', table_name='runs')
    op.drop_column('runs', 'user_id')
    # ### end Alembic commands ###
